name: Python Unit Tests

on:
  pull_request:
    branches:
      - main
    paths:
      - '**.py'  # Make sure the workflow triggers for Python files

jobs:
  test:
    runs-on: ubuntu-latest  # Use the latest Ubuntu runner

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3  # Checkout the repository code

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.13  # Choose the version of Python you want to use

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -e ".[dev]"  # Installs dependencies including dev dependencies from setup.py

      - name: Run unit tests
        run: |
          # Run tests using pytest (or your preferred test runner)
          pytest --maxfail=1 --disable-warnings -q  # Adjust test options as necessary

      - name: Upload test results (optional)
        uses: actions/upload-artifact@v4  # Updated to the latest supported version
        with:
          name: test-results
          path: ./test-reports  # Optional: specify the directory where your test results are saved
