name: Mypy Type Check

on:
  pull_request:
    branches:
      - main
    paths:
      - '**.py'  # Trigger only for Python files

jobs:
  type-check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.13  # Use the desired Python version

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -e ".[dev]"  # Ensure mypy is installed via dev dependencies

      - name: Run mypy
        run: mypy src/  # Adjust the path if needed